// generated by GAS
window.videoList = [
  "20260507_203801_[charNm=ブリジット_charId=char_21_Bridget_rate=1736_rd1=w_rdt1=0128_rd2=w_rdt2=0330_]_compressed.mp4",
  "20260507_203242_[charNm=ザトー_charId=char_9_Zato_rate=1655_rd1=w_rdt1=0118_rd2=l_rdt2=0318_rd3=w_rdt3=0443_]_compressed.mp4",
  "20260507_202753_[charNm=ラムレザル_charId=char_10_Ramlethal_rate=1663_rd1=l_rdt1=0123_rd2=w_rdt2=0246_rd3=w_rdt3=0406_]_compressed.mp4",
  "20260507_202232_[charNm=スレイヤー_charId=char_28_Slayer_rate=1699_rd1=w_rdt1=0142_rd2=w_rdt2=0432_]_compressed.mp4",
  "20260507_200626_[charNm=ブリジット_charId=char_21_Bridget_rate=1703_rd1=w_rdt1=0215_rd2=l_rdt2=0457_rd3=l_rdt3=0718_]_compressed.mp4",
  "20260507_200017_[charNm=梅喧_charId=char_19_Baiken_rate=1634_rd1=w_rdt1=0147_rd2=l_rdt2=0405_rd3=w_rdt3=0521_]_compressed.mp4",
  "20260507_195706_[charNm=メイ_charId=char_3_May_rate=1632_rd1=l_rdt1=0226_]_compressed.mp4",
  "20260507_194824_[charNm=飛鳥_charId=char_24_Asuka_rate=1733_rd1=l_rdt1=0223_rd2=w_rdt2=0453_rd3=w_rdt3=0758_]_compressed.mp4",
  "20260507_194329_[charNm=ミリア_charId=char_8_Millia_rate=1605_rd1=w_rdt1=0144_rd2=w_rdt2=0414_]_compressed.mp4",
  "20260507_193921_[charNm=スレイヤー_charId=char_28_Slayer_rate=1680_rd1=l_rdt1=0135_rd2=l_rdt2=0322_]_compressed.mp4",
  "20260507_192958_[charNm=紗夢_charId=char_33_Jam_rate=1701_rd1=l_rdt1=0105_rd2=w_rdt2=0307_rd3=l_rdt3=0533_]_compressed.mp4",
  "20260507_192658_[charNm=名残雪_charId=char_12_Nagoriyuki_rate=1618_rd1=w_rdt1=0141_]_compressed.mp4",
  "20260507_192213_[charNm=ミリア_charId=char_8_Millia_rate=1591_rd1=w_rdt1=0120_rd2=w_rdt2=0356_]_compressed.mp4",
  "20260507_191848_[charNm=アクセル_charId=char_4_Axl_rate=1617_rd1=w_rdt1=0112_rd2=w_rdt2=0238_]_compressed.mp4",
  "20260507_191546_[charNm=スレイヤー_charId=char_28_Slayer_rate=1654_rd1=l_rdt1=0107_rd2=l_rdt2=0224_]_compressed.mp4",
  "20260507_001056_[charNm=ラムレザル_charId=char_10_Ramlethal_rate=1641_rd1=w_rdt1=0144_rd2=w_rdt2=0312_]_compressed.mp4",
  "20260507_000548_[charNm=ポチョムキン_charId=char_6_Potemkin_rate=1641_rd1=l_rdt1=0156_rd2=l_rdt2=0416_]_compressed.mp4"
];
