// generated by GAS
window.videoList = [
  "20260506_235712_[charNm=ラムレザル_charId=char_10_Ramlethal_rate=1696_rd1=l_rdt1=0226_rd2=w_rdt2=0445_rd3=l_rdt3=0723_]_compressed.mp4",
  "20260506_235315_[charNm=スレイヤー_charId=char_28_Slayer_rate=1730_rd1=l_rdt1=0155_rd2=l_rdt2=0309_]_compressed.mp4",
  "20260506_234619_[charNm=チップ_charId=char_5_Chipp_rate=1716_rd1=w_rdt1=0206_rd2=l_rdt2=0427_rd3=w_rdt3=0610_]_compressed.mp4",
  "20260506_234117_[charNm=アクセル_charId=char_4_Axl_rate=1674_rd1=w_rdt1=0208_rd2=w_rdt2=0419_]_compressed.mp4",
  "20260506_233555_[charNm=ラムレザル_charId=char_10_Ramlethal_rate=1625_rd1=l_rdt1=0232_rd2=l_rdt2=0441_]_compressed.mp4",
  "20260506_232708_[charNm=ラムレザル_charId=char_10_Ramlethal_rate=1650_rd1=l_rdt1=0223_rd2=w_rdt2=0504_rd3=l_rdt3=0756_]_compressed.mp4"
];
